# Generated by Django 4.2.5 on 2023-09-07 14:02

import MyMusic.music_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Album_Name", models.CharField(max_length=30, unique=True)),
                ("Artist", models.CharField(max_length=30)),
                (
                    "Genre",
                    models.CharField(
                        choices=[
                            ("pop", "Pop Music"),
                            ("jazz", "Jazz Music"),
                            ("rnb", "R&B Music"),
                            ("country", "Country Music"),
                            ("dance", "Dance Music"),
                            ("hiphop", "Hip Hop Music"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Description", models.TextField(blank=True, null=True)),
                ("Image_URL", models.URLField()),
                (
                    "Price",
                    models.FloatField(
                        validators=[
                            MyMusic.music_app.validators.PositiveFloatValidator()
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Username",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                        ],
                    ),
                ),
                ("Email", models.CharField()),
                ("Age", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
